(("default" . ((user-emacs-directory . "~/.emacs.default")))
 ("spacemacs" . ((user-emacs-directory . "d:/gits/spacemacs")))
 ("doom" . ((user-emacs-directory . "d:/gits/doomemacs")))
 ("prelude" . ((user-emacs-directory . "d:/gits/prelude")))
 ("purcell" . ((user-emacs-directory . "d:/gits/purcell"))))
